version: '3.7'

services:
  db:
    image: postgres
    container_name: tfdb
    env_file:
      - ./digrefserver/.env
    volumes:
      - tf:/var/lib/postgresql/data
    networks:
      network:
        ipv4_address: 172.16.0.2
    restart: always

  app:
    build: .
    container_name: tfapp
    command: python manage.py runserver 0.0.0.0:8888
    ports:
      - "8888:8888"
    networks:
      network:
        ipv4_address: 172.16.0.3
    volumes:
      - .:/usr/bin/tfapp
    env_file:
      - ./digrefserver/.env
    restart: always
    depends_on:
      - db
    links:
      - "db:db"

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    env_file:
      - ./digrefserver/.env
    restart: always
    networks:
      network:
        ipv4_address: 172.16.0.4
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "5050:80"

networks:
  network:
    ipam:
      driver: default
      config:
        - subnet: "172.16.0.0/24"
          gateway: "172.16.0.1"

volumes:
  tf:
  pgadmin-data: