# Generated by Django 3.2.12 on 2022-06-10 14:04

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_auto_20220610_1638'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(check=models.Q(('sender', django.db.models.expressions.F('recipient')), _negated=True), name='check_sender_is_not_recipient'),
        ),
    ]
