# Generated by Django 3.2.12 on 2022-06-10 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_transaction_check_sender_is_not_recipient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionstate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания'),
        ),
    ]
