# Generated by Django 3.2.12 on 2022-06-28 11:16

import django.contrib.postgres.fields.citext
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0005_alter_transactionstate_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='auth_app.organization', verbose_name='Подразделение'),
        ),
        migrations.AlterField(
            model_name='account',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth_app.transaction'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='parent_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='auth_app.organization', verbose_name='Входит в'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiledepartment', to='auth_app.organization', verbose_name='Подразделение'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profileorganization', to='auth_app.organization', verbose_name='Юр.лицо'),
        ),
        migrations.AlterField(
            model_name='transactionstate',
            name='reason',
            field=django.contrib.postgres.fields.citext.CITextField(blank=True, null=True, verbose_name='Обоснование (отклонения)'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='privileged', to='auth_app.organization', verbose_name='Подразделение'),
        ),
    ]
