# Generated by Django 3.2.12 on 2022-06-29 11:22

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0006_auto_20220628_1416'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='transaction',
            name='check_sender_is_not_recipient',
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('sender', django.db.models.expressions.F('recipient')), _negated=True), models.Q(models.Q(('transaction_class', 'T'), ('transaction_class', 'R'), _connector='OR'), _negated=True), _connector='OR'), name='check_sender_is_not_recipient'),
        ),
    ]
