# Generated by Django 3.2.12 on 2022-08-04 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0008_auto_20220712_0934'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
                ('value', models.CharField(max_length=25, verbose_name='Значение')),
            ],
            options={
                'verbose_name': 'Настройки администратора',
                'db_table': 'custom_settings',
            },
        ),
        migrations.AlterField(
            model_name='userrole',
            name='role',
            field=models.CharField(choices=[('A', 'Администратор'), ('C', 'Контролер'), ('M', 'Распорядитель')], max_length=1, verbose_name='Роль'),
        ),
        migrations.AlterModelTable(
            name='account',
            table='accounts',
        ),
        migrations.AlterModelTable(
            name='contact',
            table='contacts',
        ),
        migrations.AlterModelTable(
            name='organization',
            table='organizations',
        ),
        migrations.AlterModelTable(
            name='period',
            table='periods',
        ),
        migrations.AlterModelTable(
            name='profile',
            table='profiles',
        ),
        migrations.AlterModelTable(
            name='transaction',
            table='transactions',
        ),
        migrations.AlterModelTable(
            name='transactionstate',
            table='transaction_states',
        ),
        migrations.AlterModelTable(
            name='userrole',
            table='user_roles',
        ),
        migrations.AlterModelTable(
            name='userstat',
            table='user_stats',
        ),
    ]
