# Generated by Django 3.2.12 on 2022-08-17 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0011_transaction_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='organizations', verbose_name='Фотография'),
        ),
    ]
