# Generated by Django 3.2.12 on 2022-08-17 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0012_organization_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fired_at',
            field=models.DateField(blank=True, null=True, verbose_name='Не работает с'),
        ),
    ]
