# Generated by Django 3.2.12 on 2022-08-19 15:05

import django.contrib.postgres.fields.citext
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0013_profile_fired_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='organization_type',
            field=django.contrib.postgres.fields.citext.CICharField(choices=[('R', 'Ведущая компания группы'), ('T', 'Юридическое лицо со своим премиальным фондом'), ('С', 'Юридическое лицо'), ('D', 'Подразделение'), ('М', 'Маркетплейс')], max_length=1, verbose_name='Тип организации'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='surname',
            field=django.contrib.postgres.fields.citext.CITextField(blank=True, default='', null=True, verbose_name='Фамилия'),
        ),
    ]
