# Generated by Django 3.2.12 on 2022-08-22 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0014_auto_20220819_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstat',
            name='bonus',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Премия'),
        ),
        migrations.AlterField(
            model_name='userstat',
            name='distr_burnt',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Сгоревшие как неиспользованные'),
        ),
        migrations.AlterField(
            model_name='userstat',
            name='distr_declined',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Сгоревшие (отклоненные транзакции из распределяемых)'),
        ),
        migrations.AlterField(
            model_name='userstat',
            name='distr_initial',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Получено для распределения'),
        ),
        migrations.AlterField(
            model_name='userstat',
            name='distr_redist',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Получено для распределения'),
        ),
        migrations.AlterField(
            model_name='userstat',
            name='distr_thanks',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Использовано распределяемых'),
        ),
        migrations.AlterField(
            model_name='userstat',
            name='income_at_end',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Остаток на конец периода'),
        ),
        migrations.AlterField(
            model_name='userstat',
            name='income_at_start',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Остаток на начало периода'),
        ),
        migrations.AlterField(
            model_name='userstat',
            name='income_declined',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Сгоревшие (отклоненные транзакции из своих)'),
        ),
        migrations.AlterField(
            model_name='userstat',
            name='income_exp',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Получено за стаж работы'),
        ),
        migrations.AlterField(
            model_name='userstat',
            name='income_thanks',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Получено в качестве благодарности'),
        ),
        migrations.AlterField(
            model_name='userstat',
            name='income_used_for_bonus',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Использовано для распределения премий'),
        ),
        migrations.AlterField(
            model_name='userstat',
            name='income_used_for_thanks',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Использовано своих для благодарности'),
        ),
    ]
