# Generated by Django 3.2.12 on 2022-09-05 11:51

from django.conf import settings
import django.contrib.postgres.fields.citext
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth_app', '0015_auto_20220822_1702'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Время обновления')),
                ('flags', models.CharField(blank=True, default='A', max_length=10, null=True, verbose_name='Флаги состояния')),
                ('time_from', models.DateTimeField(blank=True, null=True, verbose_name='Начало периода действия')),
                ('time_to', models.DateTimeField(blank=True, null=True, verbose_name='Окончание периода действия')),
                ('data', django.contrib.postgres.fields.citext.CITextField(verbose_name='Текст типового обоснования')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reason_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь, добавивший типовое обоснование')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.organization', verbose_name='Подразделение (область видимости)')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reason_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь, изменивший типовое обоснование')),
            ],
            options={
                'verbose_name': 'Типовые обоснования',
                'db_table': 'reasons',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Время обновления')),
                ('flags', models.CharField(blank=True, default='A', max_length=10, null=True, verbose_name='Флаги состояния')),
                ('time_from', models.DateTimeField(blank=True, null=True, verbose_name='Начало периода действия')),
                ('time_to', models.DateTimeField(blank=True, null=True, verbose_name='Окончание периода действия')),
                ('name', django.contrib.postgres.fields.citext.CICharField(max_length=100, verbose_name='Отображаемый текст тега')),
                ('info', models.TextField(blank=True, null=True, verbose_name='Пояснительный текст тега')),
                ('pict', models.ImageField(blank=True, null=True, upload_to='tags', verbose_name='Пиктограмма')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tag_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь, создавший ценность')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.organization', verbose_name='Подразделение (область видимости)')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tag_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь, изменивший ценность')),
            ],
            options={
                'verbose_name': 'Ценности',
                'db_table': 'tags',
            },
        ),
        migrations.AlterField(
            model_name='profile',
            name='tg_name',
            field=django.contrib.postgres.fields.citext.CICharField(blank=True, max_length=40, null=True, verbose_name='Имя пользователя Telegram'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='reason',
            field=django.contrib.postgres.fields.citext.CITextField(blank=True, null=True, verbose_name='Обоснование'),
        ),
        migrations.CreateModel(
            name='TagLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время назначения')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Время изменения')),
                ('flags', models.CharField(blank=True, default='A', max_length=10, null=True, verbose_name='Флаги состояния')),
                ('time_from', models.DateTimeField(blank=True, null=True, verbose_name='Начало периода действия')),
                ('time_to', models.DateTimeField(blank=True, null=True, verbose_name='Окончание периода действия')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tag_link_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь, назначивший синоним ценности')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.organization', verbose_name='Подразделение (область видимости)')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_link', to='auth_app.tag', verbose_name='Ценность')),
                ('tag_basic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_link_basic', to='auth_app.tag', verbose_name='Ценность - основной синоним')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tag_link_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь, изменивший назначение синонима ценности')),
            ],
            options={
                'verbose_name': 'Синонимы ценностей',
                'db_table': 'tag_links',
            },
        ),
        migrations.CreateModel(
            name='ReasonByTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время назначения')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Время изменения')),
                ('flags', models.CharField(blank=True, default='A', max_length=10, null=True, verbose_name='Флаги состояния')),
                ('time_from', models.DateTimeField(blank=True, null=True, verbose_name='Начало периода действия')),
                ('time_to', models.DateTimeField(blank=True, null=True, verbose_name='Окончание периода действия')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reason_by_tag_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь, назначивший типовое обоснование ценности')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.organization', verbose_name='Подразделение (область видимости)')),
                ('reason', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.reason', verbose_name='Типовое обоснование')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.tag', verbose_name='Ценность')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reason_by_tag_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь, изменивший назначение типового обоснования ценности')),
            ],
            options={
                'verbose_name': 'Назначения типовых обоснований ценностям',
                'db_table': 'reasons_by_tags',
            },
        ),
        migrations.CreateModel(
            name='ObjectTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время назначения')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Время отключения')),
                ('flags', models.CharField(blank=True, default='A', max_length=10, null=True, verbose_name='Флаги состояния')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='object_tag_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь, назначивший ценность')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.tag', verbose_name='Ценность')),
                ('tagged_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='auth_app.transaction', verbose_name='Объект')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='object_tag_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь, отключивший ценность')),
            ],
            options={
                'verbose_name': 'Назначения ценностей объектам',
                'db_table': 'object_tags',
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='reason_def',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='auth_app.reason', verbose_name='Типовое обоснование'),
        ),
    ]
