# Generated by Django 3.2.12 on 2022-09-03 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth_app', '0015_auto_20220822_1702'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeKind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название Типа Лайка')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='icons', verbose_name='Пиктограмма')),
            ],
            options={
                'db_table': 'like_kind',
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_liked', models.BooleanField(default=False, verbose_name='Выставлен')),
                ('date_created', models.DateTimeField(verbose_name='Дата выставления лайка')),
                ('date_deleted', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Дата отзыва лайка')),
                ('like_kind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like', to='auth_app.likekind', verbose_name='Тип лайка')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='auth_app.transaction', verbose_name='Транзакция')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like', to=settings.AUTH_USER_MODEL, verbose_name='Владелец Лайка')),
            ],
            options={
                'db_table': 'likes',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50, verbose_name='Текст')),
                ('date_created', models.DateTimeField(verbose_name='Дата создания')),
                ('owner_email', models.CharField(max_length=20, verbose_name='Почта')),
                ('owner_name', models.CharField(max_length=20, verbose_name='Имя')),
                ('owner_surname', models.CharField(max_length=20, verbose_name='Фамилия')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='auth_app.transaction', verbose_name='Транзакция')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to=settings.AUTH_USER_MODEL, verbose_name='Владелец Комментария')),
            ],
            options={
                'db_table': 'comments',
            },
        ),
    ]
