# Generated by Django 3.2.12 on 2022-09-06 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0016_comment_like_likekind'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='owner_email',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='owner_name',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='owner_surname',
        ),
        migrations.AddField(
            model_name='comment',
            name='date_last_modified',
            field=models.DateTimeField(null=True, verbose_name='Дата последнего изменения'),
        ),
        migrations.AddField(
            model_name='comment',
            name='is_last_comment',
            field=models.BooleanField(null=True, verbose_name='Последний комментарий в транзакции'),
        ),
        migrations.AddField(
            model_name='comment',
            name='last_comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_comment', to='auth_app.comment', verbose_name='Ссылка на предыдущий комментарий'),
        ),
        migrations.AddField(
            model_name='comment',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='comment_pictures', verbose_name='Картинка Комментария'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_commentable',
            field=models.BooleanField(default=True, verbose_name='Разрешение на добавление/изменение/удаления комментов'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_created',
            field=models.DateTimeField(null=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.CharField(max_length=50, null=True, verbose_name='Текст'),
        ),
    ]
