# Generated by Django 3.2.12 on 2022-09-05 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0016_auto_20220905_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='reason',
            name='tags',
            field=models.ManyToManyField(related_name='reasons', through='auth_app.ReasonByTag', to='auth_app.Tag'),
        ),
    ]
