# Generated by Django 3.2.12 on 2022-09-06 11:07

import django.contrib.postgres.fields.citext
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0017_reason_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='profile',
            name='job_title',
            field=django.contrib.postgres.fields.citext.CICharField(blank=True, max_length=100, null=True, verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.CharField(blank=True, choices=[('O', 'В офисе'), ('D', 'Удалённо'), ('H', 'Отпуск'), ('S', 'На больничном')], max_length=1, null=True, verbose_name='Статус сотрудника'),
        ),
        migrations.AddField(
            model_name='profile',
            name='timezone',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Разница во времени с МСК'),
        ),
        migrations.AlterField(
            model_name='objecttag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objecttags', to='auth_app.tag', verbose_name='Ценность'),
        ),
    ]
