# Generated by Django 3.2.12 on 2022-09-07 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0018_alter_comment_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='auth_app.transaction', verbose_name='Транзакция'),
        ),
    ]
