# Generated by Django 3.2.12 on 2022-09-07 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0019_alter_comment_transaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='last_comment',
            new_name='previous_comment',
        ),
        migrations.AddField(
            model_name='transaction',
            name='first_comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first_in_transaction', to='auth_app.comment', verbose_name='Первый комментарий'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='last_comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_in_transaction', to='auth_app.comment', verbose_name='Последний комментарий'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='last_event_comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_event_in_transaction', to='auth_app.comment', verbose_name='Последний добавленный или измененный комментарий'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='last_like_or_comment_change_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время последнего изменения количества лайков или последнего добавления/изменения комментария'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='auth_app.transaction', verbose_name='Транзакция'),
        ),
    ]
