# Generated by Django 3.2.12 on 2022-09-07 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0020_auto_20220907_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='first_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first_in_transaction', to='auth_app.comment', verbose_name='Первый комментарий'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='last_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_in_transaction', to='auth_app.comment', verbose_name='Последний комментарий'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='last_event_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_event_in_transaction', to='auth_app.comment', verbose_name='Последний добавленный или измененный комментарий'),
        ),
    ]
