# Generated by Django 3.2.12 on 2022-09-07 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0021_auto_20220907_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='auth_app.transaction', verbose_name='Транзакция'),
        ),
    ]
