# Generated by Django 3.2.12 on 2022-09-07 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0022_alter_comment_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='auth_app.transaction', verbose_name='Транзакция'),
        ),
    ]
