# Generated by Django 3.2.12 on 2022-09-09 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0025_likekind_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='last_like_change_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время последнего изменения количества лайков'),
        ),
    ]
