# Generated by Django 3.2.12 on 2022-09-09 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0026_transaction_last_like_change_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='last_dislike_change_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время последнего изменения количества лайков типа Дизлайк'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='last_like_change_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время последнего изменения количества лайков типа Лайк'),
        ),
    ]
