# Generated by Django 3.2.12 on 2022-09-09 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0027_auto_20220909_0349'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_counter', models.IntegerField(verbose_name='Количество лайков')),
                ('last_change_at', models.DateTimeField(blank=True, null=True, verbose_name='Время последнего изменения количества лайков типа Лайк')),
                ('like_kind', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='like_statistics', to='auth_app.likekind', verbose_name='Тип лайка')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='like_statistics', to='auth_app.transaction', verbose_name='Транзакция')),
            ],
        ),
    ]
