# Generated by Django 3.2.12 on 2022-09-09 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0028_likestatistics'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='likestatistics',
            table='like_statistics',
        ),
    ]
