# Generated by Django 3.2.12 on 2022-09-11 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0031_transaction_is_commentable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likecommentstatistics',
            name='comment_counter',
            field=models.IntegerField(default=0, verbose_name='Количество комментариев'),
        ),
    ]
