# Generated by Django 3.2.12 on 2022-09-11 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0018_auto_20220906_1407'),
        ('auth_app', '0032_alter_likecommentstatistics_comment_counter'),
    ]

    operations = [
    ]
