# Generated by Django 3.2.12 on 2022-09-13 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0033_merge_20220911_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objecttag',
            name='tagged_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='_objecttags', to='auth_app.transaction', verbose_name='Объект'),
        ),
    ]
