# Generated by Django 3.2.12 on 2022-09-21 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0035_alter_comment_previous_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_last_modified',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Дата последнего изменения'),
        ),
        migrations.AlterField(
            model_name='like',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата выставления лайка'),
        ),
        migrations.AlterField(
            model_name='like',
            name='date_deleted',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Дата отзыва лайка'),
        ),
    ]
