# Generated by Django 3.2.12 on 2022-09-21 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0036_auto_20220921_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='date_deleted',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Дата отзыва лайка'),
        ),
        migrations.AlterField(
            model_name='likecommentstatistics',
            name='last_like_or_comment_change_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Время последнего изменения количества лайков или последнего добавления/изменения комментария'),
        ),
        migrations.AlterField(
            model_name='likestatistics',
            name='last_change_at',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Время последнего изменения количества лайков'),
        ),
    ]
