# Generated by Django 3.2.12 on 2022-09-29 17:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth_app', '0039_alter_comment_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='challenge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='challengeaccount', to='auth_app.challenge', verbose_name='Челлендж'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='from_challenge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fromtransactions', to='auth_app.challenge', verbose_name='От челленджа'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='recipient_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipienttransactions', to='auth_app.account', verbose_name='Счёт получателя'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='sender_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sendertransactions', to='auth_app.account', verbose_name='Счёт отправителя'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='to_challenge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='totransactions', to='auth_app.challenge', verbose_name='Челленджу'),
        ),
        migrations.AddField(
            model_name='userstat',
            name='awarded_from_challenges',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Пользователь получил из фондов в качестве награды'),
        ),
        migrations.AddField(
            model_name='userstat',
            name='manager_redist',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Менеджер отправил для перераспределения другим'),
        ),
        migrations.AddField(
            model_name='userstat',
            name='returned_from_challenges',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Пользователь получил из фондов в качестве возврата'),
        ),
        migrations.AddField(
            model_name='userstat',
            name='sent_to_challenges',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Пользователь отправил в фонды челленджей'),
        ),
        migrations.AlterField(
            model_name='account',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incomes', to=settings.AUTH_USER_MODEL, verbose_name='Получатель'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outcomes', to=settings.AUTH_USER_MODEL, verbose_name='Отправитель'),
        ),
    ]
