# Generated by Django 3.2.6 on 2022-10-11 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0039_auto_20221006_1737'),
        ('auth_app', '0042_auto_20221007_1753'),
    ]

    operations = [
    ]
