# Generated by Django 3.2.12 on 2022-10-10 19:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth_app', '0043_alter_eventtypes_record_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionstate',
            name='controller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revised', to=settings.AUTH_USER_MODEL, verbose_name='Контролер'),
        ),
    ]
