# Generated by Django 3.2.12 on 2022-10-11 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0039_auto_20221006_1737'),
        ('auth_app', '0045_event_object_selector'),
    ]

    operations = [
    ]
