# Generated by Django 3.2.12 on 2022-10-11 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0046_merge_20221011_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='comments', verbose_name='Картинка Комментария'),
        ),
    ]
