# Generated by Django 3.2.12 on 2022-10-11 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0043_merge_0039_auto_20221006_1737_0042_auto_20221007_1753'),
        ('auth_app', '0047_alter_comment_picture'),
    ]

    operations = [
    ]
