# Generated by Django 3.2.12 on 2022-10-11 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0048_merge_20221011_1556'),
        ('auth_app', '0048_merge_20221011_1853'),
    ]

    operations = [
    ]
