# Generated by Django 3.2.12 on 2022-10-12 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0048_merge_20221012_1447'),
        ('auth_app', '0049_merge_20221011_1911'),
    ]

    operations = [
    ]
