# Generated by Django 3.2.12 on 2022-10-12 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0049_merge_20221012_1603'),
        ('auth_app', '0050_merge_20221012_1604'),
    ]

    operations = [
    ]
