# Generated by Django 3.2.12 on 2022-10-13 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0051_merge_20221012_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='object_selector',
            field=models.CharField(blank=True, choices=[('T', 'Транзакция'), ('Q', 'Челлендж'), ('R', 'Отчёт'), ('N', 'Новости'), ('A', 'Объявление')], max_length=1, null=True, verbose_name='Селектор объекта'),
        ),
    ]
