# Generated by Django 3.2.12 on 2022-10-18 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0052_alter_event_object_selector'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='challenge_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rewards', to='auth_app.challengereport', verbose_name='Отчёт о выполнении челленджа'),
        ),
    ]
