# Generated by Django 3.2.12 on 2022-10-19 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0053_transaction_challenge_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='challenge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='challengeaccount', to='auth_app.challenge', verbose_name='Челлендж'),
        ),
    ]
