# Generated by Django 3.2.12 on 2022-10-19 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0054_alter_account_challenge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='challenge_report',
        ),
        migrations.AlterField(
            model_name='account',
            name='challenge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='challengeaccount', to='auth_app.challenge', verbose_name='Челлендж'),
        ),
    ]
