# Generated by Django 3.2.12 on 2022-10-19 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0055_auto_20221019_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='challenge_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rewards', to='auth_app.challengereport', verbose_name='Отчёт о выполнении челленджа'),
        ),
        migrations.AlterField(
            model_name='account',
            name='challenge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='challengeaccount', to='auth_app.challenge', verbose_name='Челлендж'),
        ),
    ]
