# Generated by Django 3.2.12 on 2022-10-26 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0055_fcmtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='fcmtoken',
            name='device',
            field=models.CharField(default='', max_length=255, verbose_name='Устройство'),
        ),
    ]
