# Generated by Django 3.2.12 on 2022-10-31 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0058_notification_object_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='initiated_by',
        ),
    ]
