# Generated by Django 3.2.12 on 2022-11-02 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0059_remove_notification_initiated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='data',
            field=models.JSONField(blank=True, null=True, verbose_name='Данные, переданные с уведомлением'),
        ),
    ]
