# Generated by Django 3.2.12 on 2022-11-02 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0060_notification_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='from_user',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Инициировавший событие пользователь'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('L', 'Лайк'), ('C', 'Комментарий'), ('H', 'Челлендж'), ('T', 'Перевод'), ('W', 'Победа в челлендже')], max_length=1, verbose_name='Тип уведомления'),
        ),
    ]
