# Generated by Django 3.2.12 on 2022-11-10 08:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth_app', '0062_alter_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='head_of_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='heads', to=settings.AUTH_USER_MODEL, verbose_name='Руководитель организации(подразделения)'),
        ),
    ]
