# Generated by Django 3.2.12 on 2022-11-11 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0063_organization_head_of_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='challengeorganizations', to='auth_app.organization', verbose_name='Организация, где проходит челлендж'),
        ),
    ]
