# Generated by Django 3.2.12 on 2022-11-17 09:28

import django.contrib.postgres.fields.citext
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0065_alter_profile_tg_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='main_email',
            field=django.contrib.postgres.fields.citext.CICharField(blank=True, default='', max_length=255, verbose_name='Основной адрес электронной почты'),
        ),
    ]
